<a href="https://colab.research.google.com/github/Konkoxu/Python/blob/main/9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Zajecia z pythona np

In [6]:
print("hehe") 

hehe


In [ ]:
pip install numpy

In [11]:
import numpy as np
np.__version__

'1.19.5'

### Tablice jednowymiarowe

In [13]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [ ]:
help(np.array)

In [17]:
x = np.array([1,3])
x

array([1, 3])

In [18]:
print(x)

[1 3]


In [19]:
type(x)

numpy.ndarray

In [20]:
x.ndim #wymiar tablicy

1

In [21]:
x.shape

(2,)

In [22]:
x.size

2

In [23]:
x.dtype #typy wyrazen w tab

dtype('int64')

In [24]:
np.array([1.3,9.3,2.5])

array([1.3, 9.3, 2.5])

In [25]:
x = np.array([1.3,9.3,2.5])
print(x)

[1.3 9.3 2.5]


In [27]:
x.dtype

dtype('float64')

### Tablice dwuwymiarowe

In [28]:
np.array([[1,4],[-3,1]])

array([[ 1,  4],
       [-3,  1]])

In [29]:
x= np.array([[1,4],[-3,1]])
print(x)

[[ 1  4]
 [-3  1]]


In [31]:
x.ndim

2

In [32]:
x.shape

(2, 2)

In [35]:
x = np.array([[1,2,5], [4,6,2]])
print(x)

[[1 2 5]
 [4 6 2]]


In [36]:
x.shape

(2, 3)

### Tablice trzyelementowe

In [42]:
x = np.array([[[4,3,1],[3,2,1]], [[4,1,3], [4,2,1]]])
print(x)

[[[4 3 1]
  [3 2 1]]

 [[4 1 3]
  [4 2 1]]]


In [43]:
x.ndim

3

In [44]:
x = np.array([[[4,3,1],[3,2,1]],  [[4,3,1],[3,2,1]],  [[4,1,3], [4,2,1]]])
print(x)

[[[4 3 1]
  [3 2 1]]

 [[4 3 1]
  [3 2 1]]

 [[4 1 3]
  [4 2 1]]]


In [45]:
x.ndim

3

In [46]:
x.shape

(3, 2, 3)

### Typy danych

In [47]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [48]:
A = np.array([1.6,2.2,3.9])
A.dtype

dtype('float64')

In [49]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [51]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [52]:
A = np.array([1.6,2.2,3.9], dtype="int")
A.dtype

dtype('int64')

In [53]:
A

array([1, 2, 3])

In [54]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [56]:
A = np.array([24,230,120], dtype=np.int8)
A.dtype


array([ 24, -26, 120], dtype=int8)

In [58]:
A = np.array([24,230,120], dtype=np.uint8)
A.dtype

dtype('uint8')

### Tworzenie tablic

In [61]:
np.zeros(shape=(4, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
np.zeros(shape=(4, 9), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
np.ones(shape=(6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [66]:
np.ones(shape=(6, 6), dtype="int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [70]:
np.full(shape= (3,3), fill_value=5, dtype= "int")

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [71]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
np.arange(start=5,stop=11)

array([ 5,  6,  7,  8,  9, 10])

In [78]:
np.arange(start=10,stop=100, step=5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [82]:
np.arange(start=-10,stop=100, step=5)

array([-10,  -5,   0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,
        55,  60,  65,  70,  75,  80,  85,  90,  95])